version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./example/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./example/nginx/certs:/etc/nginx/certs:ro
    networks:
      default:
        aliases:
          - resource-provider.localhost.yarf.nl
          - resource-provider-api.localhost.yarf.nl
          - identity.localhost.yarf.nl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
      - resource-provider
      - resource-provider-api

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      - --import-realm
      - --log-level=debug
      - --metrics-enabled=true
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_HOSTNAME=identity.localhost.yarf.nl
      - KEYCLOAK_LOGLEVEL=DEBUG
      - KC_METRICS_ENABLED=true
      - KC_PROXY=edge
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_URL_PORT=5432
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ./example/keycloak/export:/opt/keycloak/data/import/
    depends_on:
      - postgres
    networks:
      default:
        aliases:
          - keycloak

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    networks:
      default:
        aliases:
          - postgres

  resource-provider:
    build: ./example/resource-provider
    entrypoint: docker/entrypoint-dev.sh
    command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]
    volumes:
      - ./example/resource-provider:/usr/src/app
      - .:/usr/src/django-keycloak
      - ./example/nginx/certs/ca.pem:/usr/src/ca.pem
    networks:
      default:
        aliases:
          - resource-provider

  resource-provider-api:
    build: ./example/resource-provider-api
    entrypoint: docker/entrypoint-dev.sh
    command: ["python", "manage.py", "runserver", "0.0.0.0:8002"]
    volumes:
      - ./example/resource-provider-api:/usr/src/app
      - .:/usr/src/django-keycloak
      - ./example/nginx/certs/ca.pem:/usr/src/ca.pem
    networks:
      default:
        aliases:
          - resource-provider-api
